name: Wisecow CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build Docker image
        run: docker build -t ghcr.io/pavan931/wisecow:latest .

      - name: Push Docker image
        run: docker push ghcr.io/pavan931/wisecow:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/wisecow-deployment.yaml
          kubectl apply -f k8s/wisecow-service.yaml
          kubectl apply -f k8s/wisecow-ingress.yaml

